/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EVENTOS;

import EVENTOS.Eventos;
import EVENTOS.EventosControle;
import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormEventos extends javax.swing.JFrame {

    /**
     * Creates new form FormEventos
     */
    public FormEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbDataEvento = new javax.swing.JLabel();
        lbHorarioInicio = new javax.swing.JLabel();
        lbLocalEvento = new javax.swing.JLabel();
        lbHorarioTermino = new javax.swing.JLabel();
        lbOrganizador = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbPublicoAlvo = new javax.swing.JLabel();
        lbCapacidadeMax = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        txfDataEvento = new javax.swing.JTextField();
        txfHorarioInicio = new javax.swing.JTextField();
        txfHorarioTermino = new javax.swing.JTextField();
        txfLocalEvento = new javax.swing.JTextField();
        txfDescricao = new javax.swing.JTextField();
        txfPublicoAlvo = new javax.swing.JTextField();
        txfCapacidadeMax = new javax.swing.JTextField();
        txfOrganizador = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNome.setText("Nome");

        lbDataEvento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDataEvento.setText("Data do Evento");

        lbHorarioInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHorarioInicio.setText("Horario de Inicio");

        lbLocalEvento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLocalEvento.setText("Local do Evento");

        lbHorarioTermino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHorarioTermino.setText("Horario de Termino");

        lbOrganizador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbOrganizador.setText("Organizador");

        lbDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDescricao.setText("Descrição");

        lbPublicoAlvo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPublicoAlvo.setText("Publico Alvo");

        lbCapacidadeMax.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCapacidadeMax.setText("Capacida de Maxima");

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbOrganizador)
                    .addComponent(lbDataEvento)
                    .addComponent(lbNome)
                    .addComponent(lbHorarioInicio)
                    .addComponent(lbHorarioTermino)
                    .addComponent(lbLocalEvento)
                    .addComponent(lbDescricao)
                    .addComponent(lbPublicoAlvo)
                    .addComponent(lbCapacidadeMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(txfDataEvento)
                    .addComponent(txfHorarioInicio)
                    .addComponent(txfHorarioTermino)
                    .addComponent(txfLocalEvento)
                    .addComponent(txfDescricao)
                    .addComponent(txfPublicoAlvo)
                    .addComponent(txfCapacidadeMax)
                    .addComponent(txfOrganizador))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(64, 64, 64)
                .addComponent(btnLimpar)
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDataEvento)
                            .addComponent(txfDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHorarioInicio)
                            .addComponent(txfHorarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHorarioTermino)
                            .addComponent(txfHorarioTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLocalEvento)
                            .addComponent(txfLocalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDescricao)
                            .addComponent(txfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbPublicoAlvo))
                    .addComponent(txfPublicoAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCapacidadeMax)
                    .addComponent(txfCapacidadeMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOrganizador)
                    .addComponent(txfOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGravar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        Eventos E = this.MontarEventos();
        JOptionPane.showMessageDialog(null, "Nome: "+E.getNome()+ "\nData do Evento: "+E.getDataEvento()+
                "\nHorario do Evento: "+E.getHorarioInicio()+ "\nHorario de Termino: "+E.getHorarioTermino()+
                 "\nLocal do Evento: "+E.getLocalEvento()+ "\nDescrição: "+E.getDescrição()+"\nPublico Alvo: "+E.getPublicoAlvo()+
                  "\nCapacidade maxima: "+E.getCapacidadeMaxima()+ "\nOrganizador: "+E.getOrganizador());             
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        
        Eventos E = this.MontarEventos();
         EventosControle EC = new EventosControle();
         EC.insert(EC);
    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEventos().setVisible(true);
            }
        });
    }
    public Eventos MontarEventos(){
     Eventos E = new Eventos();
     E.setNome(txfNome.getText());
     E.setDataEvento(Integer.parseInt(txfDataEvento.getText()));
     E.setHorarioInicio(Integer.parseInt(txfHorarioInicio.getText()));
     E.setHorarioTermino(Integer.parseInt(txfHorarioTermino.getText()));
     E.setLocalEvento(txfLocalEvento.getText());
     E.setDescrição(txfDescricao.getText());
     E.setPublicoAlvo(txfPublicoAlvo.getText());
     E.setCapacidadeMaxima(Integer.parseInt(txfCapacidadeMax.getText()));
     E.setOrganizador(txfOrganizador.getText());
     
     return E;
    }
    
    public void Limpar(){
     txfNome.setText("");
     txfDataEvento.setText("");
     txfHorarioInicio.setText("");
     txfHorarioTermino.setText("");
     txfLocalEvento.setText("");
     txfDescricao.setText("");
     txfPublicoAlvo.setText("");
     txfCapacidadeMax.setText("");
     txfOrganizador.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCapacidadeMax;
    private javax.swing.JLabel lbDataEvento;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbHorarioInicio;
    private javax.swing.JLabel lbHorarioTermino;
    private javax.swing.JLabel lbLocalEvento;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbOrganizador;
    private javax.swing.JLabel lbPublicoAlvo;
    private javax.swing.JTextField txfCapacidadeMax;
    private javax.swing.JTextField txfDataEvento;
    private javax.swing.JTextField txfDescricao;
    private javax.swing.JTextField txfHorarioInicio;
    private javax.swing.JTextField txfHorarioTermino;
    private javax.swing.JTextField txfLocalEvento;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfOrganizador;
    private javax.swing.JTextField txfPublicoAlvo;
    // End of variables declaration//GEN-END:variables
}
