/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CONTAS_A_PAGAR;


import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormContasAPagar extends javax.swing.JFrame {

    /**
     * Creates new form FormContasAPagar
     */
    public FormContasAPagar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDescricao = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbDatadevencimento = new javax.swing.JLabel();
        lbDatadepagamento = new javax.swing.JLabel();
        lbFornecedor = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbStatusdePagamento = new javax.swing.JLabel();
        lbMetodopagamento = new javax.swing.JLabel();
        lbObservacoes = new javax.swing.JLabel();
        txfDescricao = new javax.swing.JTextField();
        txfValor = new javax.swing.JTextField();
        txfDatavenci = new javax.swing.JTextField();
        txfDatapagamento = new javax.swing.JTextField();
        txfFornecedor = new javax.swing.JTextField();
        txfCategoria = new javax.swing.JTextField();
        txfStatusPagamento = new javax.swing.JTextField();
        txfMetodopagamento = new javax.swing.JTextField();
        txfObservacoes = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbCodContas = new javax.swing.JLabel();
        txtFCodContasApagar_ = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDescricao.setText("Descrição");

        lbValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbValor.setText("Valor");

        lbDatadevencimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDatadevencimento.setText("Data de vencimento");

        lbDatadepagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDatadepagamento.setText("Data de pagamento");

        lbFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbFornecedor.setText("Fornecedor");

        lbCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCategoria.setText("Categoria");

        lbStatusdePagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbStatusdePagamento.setText("Status de Pagamento");

        lbMetodopagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMetodopagamento.setText("Método de pagamento");

        lbObservacoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbObservacoes.setText("Observações");

        txfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDescricaoActionPerformed(evt);
            }
        });

        txfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfValorActionPerformed(evt);
            }
        });

        txfDatavenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDatavenciActionPerformed(evt);
            }
        });

        txfDatapagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDatapagamentoActionPerformed(evt);
            }
        });

        txfFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFornecedorActionPerformed(evt);
            }
        });

        txfCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCategoriaActionPerformed(evt);
            }
        });

        txfStatusPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfStatusPagamentoActionPerformed(evt);
            }
        });

        txfMetodopagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfMetodopagamentoActionPerformed(evt);
            }
        });

        txfObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfObservacoesActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbCodContas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCodContas.setText("Cod");

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addGap(21, 21, 21)
                .addComponent(btnGravar)
                .addGap(24, 24, 24)
                .addComponent(btnLimpar)
                .addGap(24, 24, 24)
                .addComponent(btnExcluir)
                .addGap(7, 7, 7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDescricao)
                    .addComponent(lbObservacoes)
                    .addComponent(lbMetodopagamento)
                    .addComponent(lbStatusdePagamento)
                    .addComponent(lbCategoria)
                    .addComponent(lbFornecedor)
                    .addComponent(lbDatadepagamento)
                    .addComponent(lbDatadevencimento)
                    .addComponent(lbValor)
                    .addComponent(lbCodContas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(txfMetodopagamento)
                    .addComponent(txfStatusPagamento)
                    .addComponent(txfCategoria)
                    .addComponent(txfFornecedor)
                    .addComponent(txfDatapagamento)
                    .addComponent(txfDatavenci)
                    .addComponent(txfValor)
                    .addComponent(txfDescricao)
                    .addComponent(txtFCodContasApagar_))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFCodContasApagar_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodContas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfDatavenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDatadevencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfDatapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDatadepagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfStatusPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStatusdePagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfMetodopagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMetodopagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbObservacoes)
                    .addComponent(txfObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnMostrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnAtualizar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Relatorio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        ContasAPagar CAP = this.MontarContasAPagar();
        if(CAP !=null){
            ContasAPagar_Controle CAC = new ContasAPagar_Controle();
            CAC.insert(CAP);
        }else{
            JOptionPane.showMessageDialog(null, "preencha todos os campos corretamente.","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        ContasAPagar CAP = this.MontarContasAPagar();
        JOptionPane.showMessageDialog(null,"Descricao: "+CAP.getDescricao()+
            "\nValor: "+CAP.getValor()+ "\nData de Vencimento: "+CAP.getDataVencimento()+
            "\nData de Pagamento: "+CAP.getDataPagamento()+ "\nFornecedor: "+CAP.getFornecedor()+
            "\nCategoria: "+CAP.getCategoria()+ "\nStatus de Pagamento: "+CAP.getStatusPagamento()+
            "\nMétodo de Pagamento: "+CAP.getMetodoPagamento()+ "Observacees: "+CAP.getObservacoes());

    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txfObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfObservacoesActionPerformed

    private void txfMetodopagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfMetodopagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfMetodopagamentoActionPerformed

    private void txfStatusPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfStatusPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfStatusPagamentoActionPerformed

    private void txfCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCategoriaActionPerformed

    private void txfFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFornecedorActionPerformed

    private void txfDatapagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDatapagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDatapagamentoActionPerformed

    private void txfDatavenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDatavenciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDatavenciActionPerformed

    private void txfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfValorActionPerformed

    private void txfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDescricaoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
            ContasAPagar CAP = this.MontarContasAPagar();
        if(CAP!= null && !txtFCodContasApagar_.getText().trim().isEmpty()){
           CAP.setCodContasAPagar(Integer.parseInt(txtFCodContasApagar_.getText()));
           ContasAPagar_Controle CPC = new ContasAPagar_Controle();
           CPC.update(CAP);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos corretamentes");
            
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         if(!txtFCodContasApagar_.getText().trim().isEmpty()){
            int Cod = Integer.parseInt(txtFCodContasApagar_.getText());
            ContasAPagar_Controle CAC = new ContasAPagar_Controle();
           CAC.delete(Cod);
        }else{
           JOptionPane.showMessageDialog(null, "Informe Novamente...");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       ContasAPagar_Controle CAC = new ContasAPagar_Controle();
       CAC.selectAll();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormContasAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormContasAPagar().setVisible(true);
            }
        });
    }
    
    public ContasAPagar MontarContasAPagar(){
    ContasAPagar CAP = new ContasAPagar();
    CAP.setDescricao(txfDescricao.getText());
    CAP.setValor(txfValor.getText());
    CAP.setDataVencimento(txfDatavenci.getText());
    CAP.setDataPagamento(txfDatapagamento.getText());
    CAP.setFornecedor(txfFornecedor.getText());
    CAP.setCategoria(txfCategoria.getText());
    CAP.setStatusPagamento(txfStatusPagamento.getText());
    CAP.setMetodoPagamento(txfMetodopagamento.getText());
    CAP.setObservacoes(txfObservacoes.getText());
    
    return CAP;
    
    }
    
    public void Limpar(){
     txfDescricao.setText("");
     txfValor.setText("");
     txfDatavenci.setText("");
     txfDatapagamento.setText("");
     txfFornecedor.setText("");
     txfCategoria.setText("");
     txfStatusPagamento.setText("");
     txfMetodopagamento.setText("");
     txfObservacoes.setText("");
     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCodContas;
    private javax.swing.JLabel lbDatadepagamento;
    private javax.swing.JLabel lbDatadevencimento;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbFornecedor;
    private javax.swing.JLabel lbMetodopagamento;
    private javax.swing.JLabel lbObservacoes;
    private javax.swing.JLabel lbStatusdePagamento;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField txfCategoria;
    private javax.swing.JTextField txfDatapagamento;
    private javax.swing.JTextField txfDatavenci;
    private javax.swing.JTextField txfDescricao;
    private javax.swing.JTextField txfFornecedor;
    private javax.swing.JTextField txfMetodopagamento;
    private javax.swing.JTextField txfObservacoes;
    private javax.swing.JTextField txfStatusPagamento;
    private javax.swing.JTextField txfValor;
    private javax.swing.JTextField txtFCodContasApagar_;
    // End of variables declaration//GEN-END:variables
}
