/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LIVROS;

/**
 *
 * @author Senac
 */
public class FormLivros extends javax.swing.JFrame {

    /**
     * Creates new form FormLivros
     */
    public FormLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        lbISBN = new javax.swing.JLabel();
        lbEditora = new javax.swing.JLabel();
        lbAnoPubli = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbNumPaginas = new javax.swing.JLabel();
        lbIdiomas = new javax.swing.JLabel();
        lbLocalBiblioteca = new javax.swing.JLabel();
        txfTitulo = new javax.swing.JTextField();
        txfAutor = new javax.swing.JTextField();
        txfISBN = new javax.swing.JTextField();
        txfEditora = new javax.swing.JTextField();
        txfAnoPubli = new javax.swing.JTextField();
        txfGenero = new javax.swing.JTextField();
        txfNumPaginas = new javax.swing.JTextField();
        txfIdiomas = new javax.swing.JTextField();
        txfLocalBiblioteca = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTitulo.setText("Titulo");

        lbAutor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAutor.setText("Autor");

        lbISBN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbISBN.setText("ISBN");

        lbEditora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEditora.setText("Editora");

        lbAnoPubli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAnoPubli.setText("Ano de publicação");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGenero.setText("Gênero");

        lbNumPaginas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNumPaginas.setText("Número de Páginas");

        lbIdiomas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbIdiomas.setText("Idiomas");

        lbLocalBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLocalBiblioteca.setText("Localização na biblioteca");

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLocalBiblioteca)
                            .addComponent(lbAutor)
                            .addComponent(lbTitulo)
                            .addComponent(lbISBN)
                            .addComponent(lbEditora)
                            .addComponent(lbAnoPubli)
                            .addComponent(lbGenero)
                            .addComponent(lbNumPaginas)
                            .addComponent(lbIdiomas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfTitulo)
                            .addComponent(txfAutor)
                            .addComponent(txfISBN)
                            .addComponent(txfEditora)
                            .addComponent(txfAnoPubli)
                            .addComponent(txfGenero)
                            .addComponent(txfNumPaginas)
                            .addComponent(txfIdiomas)
                            .addComponent(txfLocalBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnMostrar)
                        .addGap(60, 60, 60)
                        .addComponent(btnLimpar)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(txfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor)
                    .addComponent(txfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbISBN)
                    .addComponent(txfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEditora)
                    .addComponent(txfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnoPubli)
                    .addComponent(txfAnoPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenero)
                    .addComponent(txfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumPaginas)
                    .addComponent(txfNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdiomas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfLocalBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocalBiblioteca))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnLimpar))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAnoPubli;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbIdiomas;
    private javax.swing.JLabel lbLocalBiblioteca;
    private javax.swing.JLabel lbNumPaginas;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txfAnoPubli;
    private javax.swing.JTextField txfAutor;
    private javax.swing.JTextField txfEditora;
    private javax.swing.JTextField txfGenero;
    private javax.swing.JTextField txfISBN;
    private javax.swing.JTextField txfIdiomas;
    private javax.swing.JTextField txfLocalBiblioteca;
    private javax.swing.JTextField txfNumPaginas;
    private javax.swing.JTextField txfTitulo;
    // End of variables declaration//GEN-END:variables
}
